### ISSUE TITLE
每次运行到第4个step时稳定崩溃

### ISSUE THREAD

**Issue by 1212wuhu** [hiyouga/EasyR1#261]
如图，每次运行到第4个step时出现错误，附系统监测图
![Image](https://github.com/user-attachments/assets/6ac3dd97-b9e7-42db-96f1-784bc1afe5f8)

![Image](https://github.com/user-attachments/assets/e5c33079-3fa3-4923-939c-214414b66de7)

具体报错信息：
```
Processed prompts:  85%|████████████████████████████████████████████████████████████████████████████████              | 1090/1280 [04:25<01:03,  2.98it/s, est. speed input: 5620.39 toks/s, output: 3182.62 toks/s] 
Processed prompts:  86%|████████████████████████████████████████████████████████████████████████████████▍             | 1095/1280 [04:26<00:52,  3.51it/s, est. speed input: 5626.49 toks/s, output: 3195.54 toks/s] 
Processed prompts:  86%|████████████████████████████████████████████████████████████████████████████████▊             | 1100/1280 [04:27<00:44,  4.00it/s, est. speed input: 5629.87 toks/s, output: 3216.29 toks/s] 
Processed prompts:  86%|█████████████████████████████████████████████████████████████████████████████████▏            | 1105/1280 [04:27<00:36,  4.81it/s, est. speed input: 5642.93 toks/s, output: 3247.37 toks/s] 
Processed prompts:  87%|█████████████████████████████████████████████████████████████████████████████████▌            | 1110/1280 [04:28<00:28,  6.01it/s, est. speed input: 5647.78 toks/s, output: 3283.34 toks/s] 
Processed prompts:  87%|█████████████████████████████████████████████████████████████████████████████████▉            | 1115/1280 [04:30<00:37,  4.41it/s, est. speed input: 5699.91 toks/s, output: 3288.24 toks/s] 
Processed prompts:  88%|██████████████████████████████████████████████████████████████████████████████████▎           | 1120/1280 [04:31<00:34,  4.64it/s, est. speed input: 5698.38 toks/s, output: 3309.78 toks/s] 
Processed prompts:  88%|██████████████████████████████████████████████████████████████████████████████████▌           | 1125/1280 [04:33<00:46,  3.35it/s, est. speed input: 5668.08 toks/s, output: 3307.15 toks/s] 
Processed prompts:  88%|██████████████████████████████████████████████████████████████████████████████████▉           | 1130/1280 [04:33<00:34,  4.35it/s, est. speed input: 5680.38 toks/s, output: 3329.01 toks/s] 
Processed prompts:  89%|███████████████████████████████████████████████████████████████████████████████████▎          | 1135/1280 [04:35<00:35,  4.08it/s, est. speed input: 5664.32 toks/s, output: 3341.57 toks/s] 
Processed prompts:  93%|███████████████████████████████████████████████████████████████████████████████████████▍      | 1190/1280 [04:35<00:04, 22.24it/s, est. speed input: 5998.64 toks/s, output: 3655.61 toks/s] 
Processed prompts:  99%|█████████████████████████████████████████████████████████████████████████████████████████████▎| 1270/1280 [04:39<00:00, 21.70it/s, est. speed input: 6294.67 toks/s, output: 4015.70 toks/s] 
Processed prompts: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 1280/1280 [04:39<00:00,  4.57it/s, est. speed input: 6314.51 toks/s, output: 4054.14 toks/s] 
(WorkerDict pid=51994) Before vllm offload in sharding manager: 60.62 GB / 95.10 GB.                                                                                                                                 
(WorkerDict pid=52342) INFO 04-24 21:29:33 [executor_base.py:226] It took 0.244931 seconds to wake up tags ['weights']. [repeated 3x across cluster]                                                                 
(WorkerDict pid=52342) INFO 04-24 21:29:33 [executor_base.py:226] It took 0.030966 seconds to wake up tags ['kv_cache']. [repeated 3x across cluster]                                                                
(WorkerDict pid=51994) INFO 04-24 21:34:28 [block_pool.py:264] Successfully reset prefix cache                                                                                                                       
(WorkerDict pid=51994) INFO 04-24 21:34:29 [gpu_worker.py:81] Sleep mode freed 51.85 GiB memory, 8.78 GiB memory is still in use.                                                                                    
(WorkerDict pid=51994) INFO 04-24 21:34:29 [executor_base.py:210] It took 0.662000 seconds to fall asleep.                                                                                                           
(WorkerDict pid=51994) After vllm offload in sharding manager: 8.78 GB / 95.10 GB.                                                                                                                                   
(WorkerDict pid=52342) INFO 04-24 21:34:30 [block_pool.py:264] Successfully reset prefix cache [repeated 3x across cluster]                                                                                          
(WorkerDict pid=52342) INFO 04-24 21:34:30 [gpu_worker.py:81] Sleep mode freed 52.68 GiB memory, 8.88 GiB memory is still in use. [repeated 3x across cluster]                                                       
(WorkerDict pid=52342) INFO 04-24 21:34:30 [executor_base.py:210] It took 0.812007 seconds to fall asleep. [repeated 3x across cluster]                                                                              
(WorkerDict pid=52341) /root/miniconda3/envs/landai/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown 
(WorkerDict pid=52341)   warnings.warn('resource_tracker: There appear to be %d '                                                                                                                                    
(pid=49359) Episode 0:   7%|█████████▌                                                                                                                                      | 1.00/15.0 [3:21:42<47:03:49, 12.1ks/itTraceback (most recent call last):█████▏                                                                                                                                      | 5.00/134 [3:21:02<76:30:56, 2.14ks/it]
  File "/root/miniconda3/envs/landai/lib/python3.10/runpy.py", line 196, in _run_module_as_main                                                                                                                      
    return _run_code(code, main_globals, None,                                                                                                                                                                       
  File "/root/miniconda3/envs/landai/lib/python3.10/runpy.py", line 86, in _run_code███████████████████████████████████████████████████████████████████████████████████████████████| 4.00/4.00 [21:33<00:00, 248s/it]
    exec(code, run_globals): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 40.0/40.0 [06:11<00:00, 8.02s/it]
  File "/root/autodl-tmp/EasyR1/verl/trainer/main.py", line 121, in <module>
    main()
  File "/root/autodl-tmp/EasyR1/verl/trainer/main.py", line 117, in main
    ray.get(runner.run.remote(ppo_config))
  File "/root/miniconda3/envs/landai/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/root/miniconda3/envs/landai/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/landai/lib/python3.10/site-packages/ray/_private/worker.py", line 2771, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/root/miniconda3/envs/landai/lib/python3.10/site-packages/ray/_private/worker.py", line 919, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ActorUnavailableError): ray::Runner.run() (pid=49359, ip=172.17.0.12, actor_id=5c946b6c2f906554fb52a08f01000000, repr=<main.Runner object at 0x7f3eaad9cc70>)
  File "/root/autodl-tmp/EasyR1/verl/trainer/main.py", line 88, in run
    trainer.fit()
  File "/root/autodl-tmp/EasyR1/verl/trainer/ray_trainer.py", line 615, in fit
    val_metrics = self._validate()
  File "/root/autodl-tmp/EasyR1/verl/trainer/ray_trainer.py", line 308, in _validate
    test_output_gen_batch = self.actor_rollout_wg.generate_sequences(test_gen_batch)
  File "/root/autodl-tmp/EasyR1/verl/single_controller/ray/base.py", line 47, in func
    output = ray.get(output)
ray.exceptions.ActorUnavailableError: The actor fb8de7cda53355d314afddef01000000 is unavailable: The actor is temporarily unavailable: RpcError: RPC Error message: failed to connect to all addresses; last error: UNKNOWN: ipv4:172.17.0.12:39179: Failed to connect to remote host: Connection refused; RPC Error details: . The task may or maynot have been executed on the actor.
(landai) root@autodl-container-efac46bb3d-b37eb97a:~/autodl-tmp/EasyR1/examples# 
```

**Comment by 1212wuhu** [comment]
显卡为4*H20
具体参数：
```
data:
  train_files: zhou777/landai_grpo_landuse
  val_files: zhou777/landai_grpo_landuse
  prompt_key: problem
  answer_key: answer
  image_key: images
  max_prompt_length: 22000
  max_response_length: 4096
  rollout_batch_size: 512
  val_batch_size: 1024
  format_prompt: ./examples/format_prompt/math_format.jinja
  shuffle: true
  seed: 1
  max_pixels: 4194304
  # min_pixels: 262144
  filter_overlong_prompts: true

algorithm:
  adv_estimator: grpo
  disable_kl: false
  use_kl_loss: true
  kl_penalty: low_var_kl
  kl_coef: 1.0e-2

worker:
  actor:
    global_batch_size: 128
    micro_batch_size_per_device_for_update: 4
    micro_batch_size_per_device_for_experience: 20
    max_grad_norm: 1.0
    padding_free: true
    ulysses_sequence_parallel_size: 1
    model:
      model_path: Qwen/Qwen2.5-7B-Instruct
      enable_gradient_checkpointing: true
      trust_remote_code: false
      freeze_vision_tower: false
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
      strategy: adamw_bf16  # {adamw, adamw_bf16}
      lr_warmup_ratio: 0.0
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
      torch_dtype: bf16 # 开启bf16训练
    offload:
      offload_params: true  # true: more CPU memory; false: more GPU memory
      offload_optimizer: true  # true: more CPU memory; false: more GPU memory

  rollout:
    n: 5
    temperature: 0.6
    top_p: 0.95
    gpu_memory_utilization: 0.6
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 2
    limit_images: 0
    val_override_config:
      temperature: 0.5
      n: 1
    max_num_batched_tokens: 30000 

  ref:
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: true  # true: more CPU memory; false: more GPU memory
      enable_rank0_init: true
    offload:
      offload_params: false

  reward:
    reward_type: function
    score_function: ./examples/score_function/math.py:compute_score

trainer:
  total_episodes: 15
  logger: ["console", "swanlab"]
  project_name: easy_r1
  experiment_name: qwen2_5_7b_math_grpo
  n_gpus_per_node: 8
  nnodes: 1
  val_freq: 5  # -1 to disable
  val_before_train: true
  val_only: false
  val_generations_to_log: 3
  save_freq: 5  # -1 to disable
  save_limit: 3  # -1 to disable
  save_checkpoint_path: /root/autodl-tmp/EasyR1/saves
  load_checkpoint_path: null
```
