### ISSUE TITLE
GRPO训练Qwen3-4B，在几十个Step后卡住

### ISSUE THREAD

**Issue by Mr-KenLee** [hiyouga/EasyR1#289]
问题如标题所示，配置如下：
```yaml
data:
  train_files: xxx
  val_files: xxx
  prompt_key: prompt
  answer_key: answer
  image_key: images
  max_prompt_length: 3072
  max_response_length: 1280
  rollout_batch_size: 32
  val_batch_size: 128
  format_prompt: null
  override_chat_template: "{%- if messages[0].role != 'system' -%}{{ '<|im_start|>system\\nYou are a helpful assistant!<|im_end|>\\n' -}}{%- endif -%}{%- for message in messages -%}{{ '<|im_start|>' ~ message.role ~ '\\n' ~ message.content ~ '<|im_end|>' ~ '\\n' -}}{%- endfor -%}{%- if add_generation_prompt -%}{{ '<|im_start|>assistant\\n' -}}{%- if enable_thinking is defined and not enable_thinking -%}{{ '<think>\\n\\n</think>\\n\\n' -}}{%- endif -%}{%- endif -%}"
  shuffle: true
  seed: 0
  max_pixels: 4194304
  min_pixels: 262144
  filter_overlong_prompts: false

algorithm:
  adv_estimator: grpo
  disable_kl: false
  use_kl_loss: true
  kl_penalty: low_var_kl
  kl_coef: 1.0e-2

worker:
  actor:
    global_batch_size: 32
    micro_batch_size_per_device_for_update: 2
    micro_batch_size_per_device_for_experience: 8
    max_grad_norm: 1.0
    padding_free: true
    ulysses_sequence_parallel_size: 1
    model:
      model_path: xxx
      enable_gradient_checkpointing: true
      trust_remote_code: false
      freeze_vision_tower: false
    optim:
      lr: 2.0e-6
      weight_decay: 1.0e-3
      strategy: adamw
      lr_warmup_ratio: 0.1
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
    offload:
      offload_params: true
      offload_optimizer: true
  rollout:
    n: 4
    temperature: 1.0
    top_p: 0.99
    gpu_memory_utilization: 0.6
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 8
    max_num_batched_tokens: 8192
    limit_images: 0
    dtype: "bf16"
    val_override_config:
      temperature: 0.0
      n: 1  
  ref:
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: true
      enable_rank0_init: true
    offload:
      offload_params: false
  reward:
    reward_type: batch
    reward_function: ./MyConfig/reward.py:compute_score

trainer:
  total_epochs: 3
  max_steps: null
  project_name: easy_r1
  experiment_name: grpo_test
  logger: ["console"]
  nnodes: 1
  n_gpus_per_node: 8
  val_freq: 1000
  val_before_train: true
  val_only: false
  val_generations_to_log: 1
  save_freq: 1000
  save_limit: 3
  save_checkpoint_path: null
  load_checkpoint_path: null
```

环境配置为：
vllm==0.8.5.post1, pytorch==2.6.0, transformers==4.51.1, accelerate==1.6.0
